name: Publish info page

on:
  push:
    branches:
      - master
    paths:
      - '*'
      - '!README.md'
      - 'src/**'
      - 'dist/**'
      - 'avatars_original/**'
      - 'content/**'
      - '.github/workflows/main.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build yukkuricraft.net
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn Install
        run: yarn install --immutable

      - name: Yarn Setup
        run: yarn run setup

      - name: Yarn Build
        run: yarn build:ssr

      - name: Yarn Prerender
        run: yarn run prerender:ssr

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/prerender

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn Install
        run: yarn install --immutable

      - name: Run linting
        run: yarn run lint

      - name: Run YAML verification
        run: yarn run yaml-validate
