name: Test PRs for info page

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - '*'
      - '!README.md'
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Test PR with yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Yarn Setup
        run: yarn run setup

      - name: Yarn Build
        run: yarn build

      - name: Yarn Prerender
        run: yarn run prerender:ssr

      - name: Yarn Test
        run: echo "Where my tests at @katrix? :P"
