name: Test PRs for info page

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - '*'
      - '!README.md'
      - 'src/**'
      - '.github/workflows/**'

jobs:
  deploy:
    name: Test PR with yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn Install
        run: yarn install --immutable --refresh-lockfile

      - name: Yarn Setup
        run: yarn run setup

      - name: Yarn Build
        run: yarn build:ssr

      - name: Yarn Prerender
        run: yarn run prerender:ssr

      - name: Yarn Test
        run: echo "Where my tests at @katrix? :P"
